flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  #  adaptive_icon_background: "#ffffff"
  #  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true